### ISSUE TITLE
ActiveRecord::Migrator.migrate(ActiveRecord::Migrator.migrations_paths, nil)

### ISSUE THREAD

**Issue by leoplct** [zombocom/derailed_benchmarks#214]
When running

`bundle exec derailed exec perf:objects`

it crashed

```
/Users/user/.rvm/gems/ruby-3.1.2/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/load_tasks.rb:48:in `block (2 levels) in <top (required)>': undefined method `migrate' for ActiveRecord::Migrator:Class (NoMethodError)

        ActiveRecord::Migrator.migrate(ActiveRecord::Migrator.migrations_paths, nil)
from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
	from /Users/username/.rvm/gems/ruby-3.1.2/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/load_tasks.rb:69:in `block (2 levels) in <top (required)>'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
	from /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
	from /Users/username/.rvm/gems/ruby-3.1.2/gems/derailed_benchmarks-2.1.1/bin/derailed:45:in `exec'
	from /Users/username/.rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/username/.rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/username/.rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/username/.rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/username/.rvm/gems/ruby-3.1.2/gems/derailed_benchmarks-2.1.1/bin/derailed:96:in `<top (required)>'
	from /Users/username/.rvm/gems/ruby-3.1.2/bin/derailed:25:in `load'
	from /Users/username/.rvm/gems/ruby-3.1.2/bin/derailed:25:in `<main>'
	from /Users/username/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `eval'
	from /Users/username/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by fcce** [comment]
https://github.com/zombocom/derailed_benchmarks/pull/205  fix this
