### ISSUE TITLE
SSL connection error:

### ISSUE THREAD

**Issue by mattgraham** [zombocom/derailed_benchmarks#232]
I'm young in rails and trying to determine if i have a memory leak or not. While running `bundle exec derailed exec perf:objects` I'm getting the following: 

```
Booting: production
SSL connection error: error:0A000086:SSL routines::certificate verify failed
Couldn't create '' database. Please check your configuration.
/Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/mysql2_adapter.rb:46:in `rescue in new_client': SSL connection error: error:0A000086:SSL routines::certificate verify failed (ActiveRecord::ConnectionNotEstablished)
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/mysql2_adapter.rb:35:in `new_client'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/mysql2_adapter.rb:159:in `connect'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/mysql2_adapter.rb:167:in `reconnect'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:685:in `block in reconnect!'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activesupport-7.1.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:684:in `reconnect!'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:788:in `verify!'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:795:in `connect!'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:997:in `block in with_raw_connection'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activesupport-7.1.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:996:in `with_raw_connection'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:1104:in `valid_raw_connection'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:1091:in `any_raw_connection'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/mysql2_adapter.rb:181:in `get_full_version'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:87:in `get_database_version'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:374:in `database_version'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:70:in `database_version'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:200:in `database_version'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:871:in `database_version'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:657:in `check_version'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:675:in `new_connection'
	from /Users/mattgraham/.rvm/gems/ruby-3.1.3/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:720:in `checkout_new_connection'
...
```

Any thoughts?

**Comment by schneems** [comment]
https://github.com/zombocom/derailed_benchmarks#running-in-production-locally
